# Extend base image with plugins.
FROM rubykube/peatio:latest

# Copy Gemfile.plugin for installing plugins.
COPY --chown=app:app Gemfile.plugin $APP_HOME

# Install plugins.
RUN bundle install --path /opt/vendor/bundle
