source 'https://rubygems.org'

gem 'rails', '~> 4.2'
gem 'rails-i18n'

gem 'puma'
gem 'mysql2', '~> 0.3.21'
gem 'daemons-rails'
gem 'redis-rails'

gem 'rotp'
gem 'json'
gem 'jbuilder'
gem 'bcrypt'

gem 'doorkeeper', '~> 1.4.1'

gem 'omniauth',               '~> 1.2.1'
gem 'omniauth-identity',      '~> 1.1.1'
gem 'omniauth-auth0',         '~> 2.0.0'
gem 'omniauth-google-oauth2', '~> 0.3.1'

gem 'figaro'
gem 'hashie', '~> 3.0'

gem 'aasm', '~> 3.4.0'
gem 'amqp', '~> 1.3.0'
gem 'bunny', '~> 1.2.1'
gem 'cancancan'
gem 'enumerize'
gem 'datagrid'
gem 'acts-as-taggable-on'
gem 'kaminari'
gem 'paranoid2'
gem 'active_hash'
gem 'http_accept_language'
gem 'globalize', '~> 5.0'
gem 'paper_trail', '~> 3.0.1'
gem 'rails-observers'
gem 'country_select', '~> 2.1.0'

gem 'gon', '~> 5.2.0'
gem 'pusher'
gem 'eventmachine', '~> 1.0.4'
gem 'em-websocket', '~> 0.5.1'

gem 'simple_form', '~> 3.1.0'
gem 'slim-rails'
gem 'sass-rails'
gem 'coffee-rails'
gem 'uglifier'
gem 'jquery-rails'
gem 'angularjs-rails', '~> 1.3.15'
gem 'bootstrap-sass', '~> 3.2.0.2'
gem 'bootstrap-wysihtml5-rails'
gem 'font-awesome-sass'
gem 'bourbon'
gem 'momentjs-rails'
gem 'eco'
gem 'browser', '~> 0.8.0'
gem 'rbtree'
gem 'liability-proof', '0.0.9'
gem 'whenever', '~> 0.9.2'
gem 'grape', '~> 1.0.1'
gem 'grape-entity', '~> 0.5.2'
gem 'grape-swagger', '~> 0.27.3'
gem 'grape-swagger-ui', '~> 2.2.8'
gem 'rack-attack', '~> 3.0.0'
gem 'easy_table'
gem 'phonelib', '~> 0.3.5'
gem 'unread', github: 'peatio/unread'
gem 'carrierwave', '~> 0.10.0'
gem 'simple_captcha2', require: 'simple_captcha'
gem 'rest-client', '~> 1.6.8'
gem 'jwt', '~> 1.5'
gem 'email_validator', '~> 1.6'

group :development, :test do
  gem 'factory_bot_rails'
  gem 'faker', '~> 1.4.3'
  gem 'meta_request'
  gem 'better_errors'
  gem 'binding_of_caller'
  gem 'pry-rails'
  gem 'quiet_assets'
  gem 'timecop'
  gem 'dotenv-rails'
  gem 'rspec-rails'
  gem 'byebug'
end

group :test do
  gem 'capybara'
  gem 'database_cleaner'
  gem 'launchy'
  gem 'mocha', require: false
  gem 'selenium-webdriver'

  # rspec-rails rely on test-unit if rails version less then 4.1.0
  # but test-unit has been removed from ruby core since 2.2.0
  gem 'test-unit'
end
