source 'https://rubygems.org'

gem 'rails'
gem 'rails-i18n'

gem 'mysql2'
gem 'daemons-rails'
gem 'redis-rails'

gem 'rotp'
gem 'json'
gem 'jbuilder'
gem 'bcrypt-ruby', '~> 3.1.2'

gem 'omniauth'
gem 'omniauth-identity'

gem 'figaro'
gem 'settingslogic'
gem 'hashie'

gem 'aasm'
gem 'amqp', '~> 1.3.0'
gem 'bunny', '~> 1.2.1'
gem 'cancancan'
gem 'enumerize'
gem 'datagrid'
gem 'cached_resource'
gem 'acts-as-taggable-on'
gem 'kaminari'
gem 'paranoid2'
gem 'active_hash'
gem 'http_accept_language'
gem "globalize", "~> 4.0.0"
gem 'paper_trail', '~> 3.0.1'
gem 'rails-observers'

gem 'gon'
gem 'pusher'
gem 'eventmachine', '~> 1.0.3'
gem 'em-websocket', '~> 0.5.1'

gem 'simple_form', '3.0.1'
gem 'slim-rails'
gem 'sass-rails'
gem 'coffee-rails'
gem 'uglifier'
gem 'therubyracer'
gem "jquery-rails"
gem 'bootstrap-sass'
gem 'bootstrap-wysihtml5-rails'
gem 'font-awesome-sass'
gem 'momentjs-rails'
gem 'flot-rails'
gem 'handlebars_assets'
gem 'browser'
gem 'introjs-rails'
gem 'rbtree'
gem 'liability-proof', '0.0.9'
gem 'whenever', '~> 0.9.2'
gem 'grape', '~> 0.7.0'
gem 'grape-entity', '~> 0.4.2'
gem 'grape-swagger', '~> 0.7.2'
gem 'rack-attack', '~> 3.0.0'
gem 'easy_table'
gem 'ransack', git: 'https://github.com/activerecord-hackery/ransack.git', branch: 'rails-4'
gem 'phonelib'
gem 'twilio-ruby', '~> 3.11'

group :development, :test do
  gem 'factory_girl_rails'
  gem 'faker'
  gem 'mina'
  gem 'mina-slack', git: 'https://github.com/tomlion/mina-slack.git'
  gem 'meta_request'
  gem 'better_errors'
  gem 'binding_of_caller'
  gem 'pry-rails'
  gem 'quiet_assets'
  gem 'mails_viewer'
  gem 'timecop'
  gem 'dotenv-rails'
  gem 'rspec-rails'
  gem 'byebug'
  gem "annotate", '~> 2.5.0'
end

group :test do
  gem 'database_cleaner'
  gem 'mocha', :require => false
  gem 'shoulda-matchers'
  gem 'capybara'
  gem 'launchy'
  gem 'selenium-webdriver'
  gem 'poltergeist'
end

gem 'unicorn'
