#!/usr/bin/env ruby
require 'rubygems'
require 'daemons/rails/config'

config = Daemons::Rails::Config.for_controller(File.expand_path(__FILE__))
config[:app_name] = 'peatio:amqp:pusher'
Daemons::Rails.run config[:script], config.to_hash
