platform: linux
image_resource:
  type: docker-image
  source:
    repository: alpine/git
inputs:
  - name: repo
outputs:
  - name: tag
run:
  dir: repo
  path: sh
  args:
    - "-exc"
    - echo -n "$(cat VERSION)-${type}-$(git rev-parse --short=8 HEAD)" > ../tag/name
