platform: linux

run:
  path: sh
  args:
    - "-exc"
    - |
      cd $APP_HOME
      RAILS_ENV=test bundle exec rake tmp:create db:drop db:create db:migrate
      bundle exec rspec --exclude-pattern='spec/features/**/*' spec
