- id: 1
  code: 004
  name: 臺灣銀行
- id: 2
  code: 005
  name: 土地銀行
- id: 3
  code: 006  
  name: 合作商銀
- id: 4
  code: 007
  name: 第一銀行
- id: 5
  code: 008
  name: 華南商行
- id: 6
  code: 009
  name: 彰化商銀
- id: 7
  code: 011
  name: 上海銀行
- id: 8
  code: 012
  name: 台北商銀
- id: 9
  code: 013
  name: 國泰商銀
- id: 10
  code: 017
  name: 兆豐商銀
- id: 11
  code: 021
  name: 花旗銀行
- id: 12
  code: 039
  name: 澳盛商銀
- id: 13
  code: 016
  name: 高雄銀行
- id: 14
  code: 050
  name: 臺灣中小企銀
- id: 15
  code: 052
  name: 渣打商銀
- id: 16
  code: 053
  name: 台中商銀
- id: 17
  code: 054
  name: 京城商銀