- id: 200
  key: satoshi
  currency: btc
  type: DepositChannelSatoshi
  confirm: 1
  confirm_max: 6
- id: 400
  key: bank
  currency: cny
  type: DepositChannelBank
  account_bank: '#Fake Bank Name#'
  account_holder: '#Fake Card Holder#'
  account_number: '#Fake Card Number#'
