apiVersion: batch/v1
kind: Job
metadata:
  name: "{{ .Release.Name }}-prepare-db-{{ randNumeric 5 }}"
  labels:
    app: {{ template "fullname" . }}
    component: peatio
  annotations:
    "helm.sh/hook": pre-install,pre-upgrade
spec:
  template:
    metadata:
      name: "{{ .Release.Name }}"
      labels:
        app: {{ template "fullname" . }}
        component: peatio
    spec:
      restartPolicy: OnFailure
      containers:
        - name: prepare-db
          image: {{ template "image" . }}
          command: ["rake", "db:create", "db:migrate"]
          env:
{{ include "prepare-db-env" . | indent 12 }}
